// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimulatedBank.Data;

#nullable disable

namespace SimulatedBank.Migrations
{
    [DbContext(typeof(BankContext))]
    [Migration("20260511104401_AddBankTransactionIdempotencyAndConcurrency")]
    partial class AddBankTransactionIdempotencyAndConcurrency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimulatedBank.Entities.Bank", b =>
                {
                    b.Property<Guid>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IFSCCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BankId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            BankId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            IFSCCode = "WPAY0001",
                            Name = "WPay Simulated Bank"
                        });
                });

            modelBuilder.Entity("SimulatedBank.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("BankAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BankId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<Guid?>("ExternalBankAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("BankAccountId");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.HasIndex("BankId");

                    b.HasIndex("ExternalBankAccountId")
                        .IsUnique()
                        .HasFilter("[ExternalBankAccountId] IS NOT NULL AND [ExternalBankAccountId] != '00000000-0000-0000-0000-000000000000'");

                    b.ToTable("BankAccounts");

                    b.HasData(
                        new
                        {
                            BankAccountId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AccountHolderName = "Sunidhi Sharma",
                            AccountNumber = "SB1000000001",
                            AccountType = "Savings",
                            Balance = 50000m,
                            BankId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BankName = "WPay Simulated Bank",
                            CreatedAt = new DateTime(2026, 5, 11, 10, 44, 1, 60, DateTimeKind.Utc).AddTicks(6622),
                            IsActive = true
                        },
                        new
                        {
                            BankAccountId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AccountHolderName = "Rahul Sharma",
                            AccountNumber = "SB1000000002",
                            AccountType = "Savings",
                            Balance = 100000m,
                            BankId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BankName = "WPay Simulated Bank",
                            CreatedAt = new DateTime(2026, 5, 11, 10, 44, 1, 60, DateTimeKind.Utc).AddTicks(6627),
                            ExternalBankAccountId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true
                        },
                        new
                        {
                            BankAccountId = new Guid("33333333-3333-3333-3333-333333333333"),
                            AccountHolderName = "Sujal Sharma",
                            AccountNumber = "SB1000000003",
                            AccountType = "Savings",
                            Balance = 750000m,
                            BankId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BankName = "WPay Simulated Bank",
                            CreatedAt = new DateTime(2026, 5, 11, 10, 44, 1, 60, DateTimeKind.Utc).AddTicks(6631),
                            ExternalBankAccountId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true
                        },
                        new
                        {
                            BankAccountId = new Guid("44444444-4444-4444-4444-444444444444"),
                            AccountHolderName = "Priya Reddy",
                            AccountNumber = "SB1000000004",
                            AccountType = "Savings",
                            Balance = 62000m,
                            BankId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BankName = "WPay Simulated Bank",
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalBankAccountId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true
                        },
                        new
                        {
                            BankAccountId = new Guid("55555555-5555-5555-5555-555555555555"),
                            AccountHolderName = "Arjun Patel",
                            AccountNumber = "SB1000000005",
                            AccountType = "Current",
                            Balance = 88000m,
                            BankId = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            BankName = "WPay Simulated Bank",
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalBankAccountId = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("SimulatedBank.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ErrorCode")
                        .HasColumnType("int");

                    b.Property<Guid>("ExternalReferenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TransactionId");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("ExternalReferenceId", "Type")
                        .IsUnique()
                        .HasFilter("[ExternalReferenceId] != '00000000-0000-0000-0000-000000000000'");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SimulatedBank.Entities.VerificationToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("ExpiryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("DATEADD(MINUTE, 5, GETUTCDATE())");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TokenId");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("VerificationTokens");
                });

            modelBuilder.Entity("SimulatedBank.Entities.BankAccount", b =>
                {
                    b.HasOne("SimulatedBank.Entities.Bank", "Bank")
                        .WithMany("BankAccounts")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("SimulatedBank.Entities.Transaction", b =>
                {
                    b.HasOne("SimulatedBank.Entities.BankAccount", null)
                        .WithMany("Transactions")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimulatedBank.Entities.VerificationToken", b =>
                {
                    b.HasOne("SimulatedBank.Entities.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BankAccount");
                });

            modelBuilder.Entity("SimulatedBank.Entities.Bank", b =>
                {
                    b.Navigation("BankAccounts");
                });

            modelBuilder.Entity("SimulatedBank.Entities.BankAccount", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
